FROM php:5-fpm-alpine

RUN apk add --update php5 php5-cli php5-json php5-phar libxml2-dev libcurl curl-dev php5-pdo curl postgresql-dev php5-ctype php5-pdo_pgsql php5-curl php5-dom php5-xml tzdata

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN printf '[PHP]\ndate.timezone = "America/Sao_Paulo"\n' > /usr/local/etc/php/conf.d/tzone.ini
RUN docker-php-ext-install pdo_pgsql