<?php

namespace MapasCulturais\DoctrineProxies\__CG__\MapasCulturais\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \MapasCulturais\Entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '__enableMagicGetterHook', 'id', 'authProvider', 'authUid', 'email', 'lastLoginTimestamp', 'createTimestamp', 'status', 'roles', 'agents', 'profile', '_userProcurations', '_attorneyProcurations', '__metadata', '_isDeleting', '_validationErrors', '' . "\0" . 'MapasCulturais\\Entities\\User' . "\0" . '__changedMetadata', '' . "\0" . 'MapasCulturais\\Entities\\User' . "\0" . '__createdMetadata'];
        }

        return ['__isInitialized__', '__enableMagicGetterHook', 'id', 'authProvider', 'authUid', 'email', 'lastLoginTimestamp', 'createTimestamp', 'status', 'roles', 'agents', 'profile', '_userProcurations', '_attorneyProcurations', '__metadata', '_isDeleting', '_validationErrors', '' . "\0" . 'MapasCulturais\\Entities\\User' . "\0" . '__changedMetadata', '' . "\0" . 'MapasCulturais\\Entities\\User' . "\0" . '__createdMetadata'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIsDeleting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleting', []);

        return parent::getIsDeleting();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityTypeLabel($plural = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityTypeLabel', [$plural]);

        return parent::getEntityTypeLabel($plural);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnerUser', []);

        return parent::getOwnerUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthProvider($provider_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthProvider', [$provider_name]);

        return parent::setAuthProvider($provider_name);
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile(\MapasCulturais\Entities\Agent $agent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', [$agent]);

        return parent::setProfile($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(string $role_name, $subsite_id = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$role_name, $subsite_id]);

        return parent::addRole($role_name, $subsite_id);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(string $role_name, $subsite_id = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$role_name, $subsite_id]);

        return parent::removeRole($role_name, $subsite_id);
    }

    /**
     * {@inheritDoc}
     */
    public function can(string $action, \MapasCulturais\Entity $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'can', [$action, $entity]);

        return parent::can($action, $entity);
    }

    /**
     * {@inheritDoc}
     */
    public function is(string $role_name, $subsite_id = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'is', [$role_name, $subsite_id]);

        return parent::is($role_name, $subsite_id);
    }

    /**
     * {@inheritDoc}
     */
    public function makeAttorney($action, \DateTime $valid_until = NULL, \MapasCulturais\Entities\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'makeAttorney', [$action, $valid_until, $user]);

        return parent::makeAttorney($action, $valid_until, $user);
    }

    /**
     * {@inheritDoc}
     */
    public function isAttorney($action, $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAttorney', [$action, $user]);

        return parent::isAttorney($action, $user);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationsByStatus($status = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationsByStatus', [$status]);

        return parent::getRegistrationsByStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledAgents', []);

        return parent::getEnabledAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftAgents', []);

        return parent::getDraftAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrashedAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrashedAgents', []);

        return parent::getTrashedAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabledAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabledAgents', []);

        return parent::getDisabledAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitedAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitedAgents', []);

        return parent::getInvitedAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedAgents', []);

        return parent::getRelatedAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedAgents', []);

        return parent::getArchivedAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getHasControlAgents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasControlAgents', []);

        return parent::getHasControlAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function getAgentWithControl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgentWithControl', []);

        return parent::getAgentWithControl();
    }

    /**
     * {@inheritDoc}
     */
    public function getSpaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpaces', []);

        return parent::getSpaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledSpaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledSpaces', []);

        return parent::getEnabledSpaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftSpaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftSpaces', []);

        return parent::getDraftSpaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrashedSpaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrashedSpaces', []);

        return parent::getTrashedSpaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabledSpaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabledSpaces', []);

        return parent::getDisabledSpaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedSpaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedSpaces', []);

        return parent::getArchivedSpaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getHasControlSpaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasControlSpaces', []);

        return parent::getHasControlSpaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvents', []);

        return parent::getEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledEvents', []);

        return parent::getEnabledEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftEvents', []);

        return parent::getDraftEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrashedEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrashedEvents', []);

        return parent::getTrashedEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabledEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabledEvents', []);

        return parent::getDisabledEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getHasControlEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasControlEvents', []);

        return parent::getHasControlEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedEvents', []);

        return parent::getArchivedEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjects', []);

        return parent::getProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledProjects', []);

        return parent::getEnabledProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftProjects', []);

        return parent::getDraftProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrashedProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrashedProjects', []);

        return parent::getTrashedProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabledProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabledProjects', []);

        return parent::getDisabledProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedProjects', []);

        return parent::getArchivedProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getHasControlProjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasControlProjects', []);

        return parent::getHasControlProjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportunities', []);

        return parent::getOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledOpportunities', []);

        return parent::getEnabledOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftOpportunities', []);

        return parent::getDraftOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrashedOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrashedOpportunities', []);

        return parent::getTrashedOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabledOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabledOpportunities', []);

        return parent::getDisabledOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedOpportunities', []);

        return parent::getArchivedOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getHasControlOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasControlOpportunities', []);

        return parent::getHasControlOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportunitiesCanBeEvaluated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportunitiesCanBeEvaluated', []);

        return parent::getOpportunitiesCanBeEvaluated();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubsite($status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubsite', [$status]);

        return parent::getSubsite($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledSubsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledSubsite', []);

        return parent::getEnabledSubsite();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftSubsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftSubsite', []);

        return parent::getDraftSubsite();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrashedSubsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrashedSubsite', []);

        return parent::getTrashedSubsite();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabledSubsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabledSubsite', []);

        return parent::getDisabledSubsite();
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedSubsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedSubsite', []);

        return parent::getArchivedSubsite();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeals', []);

        return parent::getSeals();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledSeals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledSeals', []);

        return parent::getEnabledSeals();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftSeals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftSeals', []);

        return parent::getDraftSeals();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrashedSeals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrashedSeals', []);

        return parent::getTrashedSeals();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabledSeals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabledSeals', []);

        return parent::getDisabledSeals();
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedSeals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedSeals', []);

        return parent::getArchivedSeals();
    }

    /**
     * {@inheritDoc}
     */
    public function getHasControlSeals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasControlSeals', []);

        return parent::getHasControlSeals();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotifications($status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotifications', [$status]);

        return parent::getNotifications($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntitiesNotifications($app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntitiesNotifications', [$app]);

        return parent::getEntitiesNotifications($app);
    }

    /**
     * {@inheritDoc}
     */
    public function delete($flush = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', [$flush]);

        return parent::delete($flush);
    }

    /**
     * {@inheritDoc}
     */
    public function transferEntitiesTo(\MapasCulturais\Entities\Agent $target_agent, $flush = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'transferEntitiesTo', [$target_agent, $flush]);

        return parent::transferEntitiesTo($target_agent, $flush);
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist($args = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', [$args]);

        return parent::prePersist($args);
    }

    /**
     * {@inheritDoc}
     */
    public function postPersist($args = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postPersist', [$args]);

        return parent::postPersist($args);
    }

    /**
     * {@inheritDoc}
     */
    public function preRemove($args = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preRemove', [$args]);

        return parent::preRemove($args);
    }

    /**
     * {@inheritDoc}
     */
    public function postRemove($args = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postRemove', [$args]);

        return parent::postRemove($args);
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate($args = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', [$args]);

        return parent::preUpdate($args);
    }

    /**
     * {@inheritDoc}
     */
    public function postUpdate($args = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postUpdate', [$args]);

        return parent::postUpdate($args);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function refresh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'refresh', []);

        return parent::refresh();
    }

    /**
     * {@inheritDoc}
     */
    public function equals($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'equals', [$entity]);

        return parent::equals($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', []);

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function isArchived()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isArchived', []);

        return parent::isArchived();
    }

    /**
     * {@inheritDoc}
     */
    public function simplify($properties = 'id,name')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'simplify', [$properties]);

        return parent::simplify($properties);
    }

    /**
     * {@inheritDoc}
     */
    public function dump()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dump', []);

        return parent::dump();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function canUser($action, $userOrAgent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canUser', [$action, $userOrAgent]);

        return parent::canUser($action, $userOrAgent);
    }

    /**
     * {@inheritDoc}
     */
    public function isUserAdmin(\MapasCulturais\UserInterface $user, $role = 'admin')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUserAdmin', [$user, $role]);

        return parent::isUserAdmin($user, $role);
    }

    /**
     * {@inheritDoc}
     */
    public function checkPermission($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkPermission', [$action]);

        return parent::checkPermission($action);
    }

    /**
     * {@inheritDoc}
     */
    public function isPropertyRequired($entity, $property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPropertyRequired', [$entity, $property]);

        return parent::isPropertyRequired($entity, $property);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntity', []);

        return parent::getEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function getSingleUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSingleUrl', []);

        return parent::getSingleUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getEditUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditUrl', []);

        return parent::getEditUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleteUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleteUrl', []);

        return parent::getDeleteUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getController()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getController', []);

        return parent::getController();
    }

    /**
     * {@inheritDoc}
     */
    public function getControllerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControllerId', []);

        return parent::getControllerId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityType', []);

        return parent::getEntityType();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityState', []);

        return parent::getEntityState();
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', []);

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function saveFlush($flush = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveFlush', [$flush]);

        return parent::saveFlush($flush);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationErrors', []);

        return parent::getValidationErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function repo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'repo', []);

        return parent::repo();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($name, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$name, $arguments]);

        return parent::__call($name, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function __metadata__get($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__metadata__get', [$name]);

        return parent::__metadata__get($name);
    }

    /**
     * {@inheritDoc}
     */
    public function __metadata__set($name, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__metadata__set', [$name, $value]);

        return parent::__metadata__set($name, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisteredMetadata($meta_key = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisteredMetadata', [$meta_key]);

        return parent::getRegisteredMetadata($meta_key);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadata($meta_key = NULL, $return_metadata_object = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadata', [$meta_key, $return_metadata_object]);

        return parent::getMetadata($meta_key, $return_metadata_object);
    }

    /**
     * {@inheritDoc}
     */
    public function getChangedMetadata()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChangedMetadata', []);

        return parent::getChangedMetadata();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetadata($meta_key, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetadata', [$meta_key, $value]);

        return parent::setMetadata($meta_key, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadataValidationErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadataValidationErrors', []);

        return parent::getMetadataValidationErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function saveMetadata()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveMetadata', []);

        return parent::saveMetadata();
    }

    /**
     * {@inheritDoc}
     */
    public function getInstagramUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstagramUrl', []);

        return parent::getInstagramUrl();
    }

}
